### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OpenPose'

### ISSUE THREAD

**Issue by arthur-yh** [RobertGCNiu/Tello-Gesture-Control#1]
Hello, when I run `python2 video_effect.py` under the dir ~/openpose/build/examples/tutorial_api_python, there existed a problem 
`Traceback (most recent call last):
  File "video_effect.py", line 38, in <module>
    openpose = op.OpenPose(params)
AttributeError: 'module' object has no attribute 'OpenPose'
`
the dir"tutorial_api_python" is the dir of your project"tutorial_python".
I have build openpose correctly and passed the test in quick start of [https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md#quick-start](url) .
Then I find an code named "openpose.py" in /home/yhh/openpose/build/examples/tutorial_api_python/python/openpose , where there defines an class object "OpenPose". How can I handle it to solve the AttributeError above?
Thank you and Thank you for your work.

**Comment by arthur-yh** [comment]
I solved it by myself. I installed the openpose_master release which is not compatible with this project. After I installed openpose-1.4.0, no error occurs. But when I run `python2 video_effect.py` , it could not get the effect where the project shows. The image is not updated and tello could not take off although I show the take-off gesture to it many times. Now I try to read the code carefully to solve this bug.

**Comment by RobertGCNiu** [comment]
The program **video_effect.py** doesn't require OpenPose lib. Actually, you can directly run the program and test the video from Tello.

**Comment by arthur-yh** [comment]
I find the problem in code 126 line 
`frame_skip = int((time.time() - start_time)/frame.time_base)`
which will cause frame_skip turn to be very huge about 2322345 after the frame_skip turn from 300 to 0, so the image will not be updated only showing the first image.
I delete this line, adding the following code:
`		if frame.time_base < 1.0/60:
                    time_base = 1.0/60
                else:
                    time_base = frame.time_base
                frame_skip = int((time.time() - start_time)/time_base)
`

Then everything is fine.
