### ISSUE TITLE
How to apply the KNN to match gesture?

### ISSUE THREAD

**Issue by Rookielike** [RobertGCNiu/Tello-Gesture-Control#4]
Thanks for your sharing.
Can you tell me the detail about the matching in gestures using KNN?I am a little confused
Thanks

**Comment by RobertGCNiu** [comment]
The kNN algorithm is implemented in this [code](https://github.com/RobertGCNiu/UAV-Gesture-Control_Python/blob/master/tutorial_python/kNN/kNNtest.py). It's a very simple idea. I measure the Euclidean distance between input vectors and pre-defined pose. Then the input vectors are clustered to the pose with minimal distance.

**Comment by Rookielike** [comment]
thanks for response
