### ISSUE TITLE
一点问题

### ISSUE THREAD

**Issue by buliu0329** [RobertGCNiu/Tello-Gesture-Control#7]
想请问如何执行video_effect.py这个档案，以及请将文件“ /python_tutorial”复制到计算机路径“ openpose / build / examples / python_tutorial”分别是指tutorial_python与tutorial_api_python吗?
又或者是我有遗漏掉了什么文件呢?
![74978106_2280314355599844_7058720103197573120_n](https://user-images.githubusercontent.com/30814641/67191994-4891e900-f425-11e9-83e1-adc6eca37aa7.png)

**Comment by RobertGCNiu** [comment]
1. 直接运行Python video_effect.py (需要Pip install tellopy)。用tellopy的主要目的是将video stream变成frame，方便后续CV处理
2. 只需要复制到Tutorial_python下即可，事实上，如果添加到bashrc中，不用复制，在任何路径下都可以运行。复制只是因为我的Openpose添加环境变量失败，所以就在openpose下运行了

**Comment by buliu0329** [comment]
我看了看官方的PYTHON范例程式码，在01_body_from_image.py里第24行写著from openpose import ""pyopenpose"" as op，但是video_effect.py里的第17行是from openpose import ""openpose"" as op，想请问是不是不适用于新的openpose呢？(pyopenpose与openpose的不同)

**Comment by RobertGCNiu** [comment]
应该是名字更新了，具体的需要你去看一下openpose的更新，我已经好久没看过了。

**Comment by buliu0329** [comment]
好的，感谢回复
