### ISSUE TITLE
關於openpose與程式版本不同的問題

### ISSUE THREAD

**Issue by JOJO9527realy** [RobertGCNiu/Tello-Gesture-Control#8]
如題，我試過了很多辦法卻還是無法順利執行程式，我朋友指出問題為openpose版本不同所致，但作為一個程式新手實在不知道該如何修改程式。還請大老幫幫我。感謝

**Comment by RobertGCNiu** [comment]
OpenPose的版本确实已经变了，你有试过单独运行openpose吗？使用电脑自带摄像头，参考这里： https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md#quick-start

**Comment by JOJO9527realy** [comment]
OpenPose單獨運行沒問題，只是運行您的程式就會出現錯誤。

**Comment by RobertGCNiu** [comment]
报错是怎么样的？

**Comment by JOJO9527realy** [comment]
抱歉過好幾天才回覆，最近我媽媽生病一直在照顧他，我運行ㄒvideo_effect.py檔的時候出現以下錯誤訊息
 python video_effect.py
Traceback (most recent call last):
  File "video_effect.py", line 20, in <module>
    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
Exception: Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?

**Comment by RobertGCNiu** [comment]
这是openpose的问题，你需要
1. 看openpose是否添加到环境变量中
2. 在用Cmake的时候要勾选Build_Python的选项
3. 检查python的openpose能否使用。因为摄像头的openpose没有调用python，所以不能说明你的python接口没有问题。

**Comment by JOJO9527realy** [comment]
請問您當初在建置此系統的時候，所使用的openpose版本為何？我想重裝openpose看可不可以解決此問題。

**Comment by RobertGCNiu** [comment]
![图片](https://user-images.githubusercontent.com/16495354/69700389-4e19d780-1125-11ea-8d7b-1f6619d9e047.png)
不建议你去找之前的版本，最新版本完全可以用的。你试一下这个，如果不行的话，说明你的openpose没有装好，可以试试重装https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/modules/python_module.md

**Comment by JOJO9527realy** [comment]
好的，我會試試看
